version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - miguelguedelha-com
  redis-commander:
    container_name: redis-commander
    depends_on:
      - redis
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    ports:
      - "8081:8081"
    networks:
      - miguelguedelha-com
    environment:
      - REDIS_HOSTS=redis
      - HTTP_USER=${REDIS_COMMANDER_HTTP_USER}
      - HTTP_PASSWORD=${REDIS_COMMANDER_HTTP_PASSWORD}
      - TRUST_PROXY=true
      - SCAN_COUNT=10000
      - URL_PREFIX=/redis-ui
networks:
  miguelguedelha-com:
    external: false
    name: miguelguedelha-com
